In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
marketing = pd.read_csv("marketing.csv", encoding="latin-1")

In [3]:
marketing.isnull().sum()
marketing.head()

,Order ID,Marital_Status,Income,Dt_Customer,Recency,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,CA-2016-152156,Single,58138.0,2012-09-04,58.0,3.0,8.0,10.0,4.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,11.0,1.0
1,CA-2016-152156,Single,46344.0,2014-03-08,38.0,2.0,1.0,1.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,11.0,0.0
2,CA-2016-138688,Together,71613.0,2013-08-21,26.0,1.0,8.0,2.0,10.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,11.0,0.0
3,US-2015-108966,Together,26646.0,2014-02-10,26.0,2.0,2.0,0.0,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,11.0,0.0
4,US-2015-108966,Married,58293.0,2014-01-19,94.0,5.0,5.0,3.0,6.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,11.0,0.0

In [4]:
marketing.count

<bound method DataFrame.count of             Order ID Marital_Status   Income Dt_Customer  Recency  \
0     CA-2016-152156         Single  58138.0  2012-09-04     58.0
1     CA-2016-152156         Single  46344.0  2014-03-08     38.0
2     CA-2016-138688       Together  71613.0  2013-08-21     26.0
3     US-2015-108966       Together  26646.0  2014-02-10     26.0
4     US-2015-108966        Married  58293.0  2014-01-19     94.0
...              ...            ...      ...         ...      ...
9989  CA-2014-110422            NaN      NaN         NaN      NaN
9990  CA-2017-121258            NaN      NaN         NaN      NaN
9991  CA-2017-121258            NaN      NaN         NaN      NaN
9992  CA-2017-121258            NaN      NaN         NaN      NaN
9993  CA-2017-119914            NaN      NaN         NaN      NaN

      NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0                   3.0              8.0                 10.0
1                   2.0              1.0                  1.0
2                   1.0              8.0                  2.0
3                   2.0              2.0                  0.0
4                   5.0              5.0                  3.0
...                 ...              ...                  ...
9989                NaN              NaN                  NaN
9990                NaN              NaN                  NaN
9991                NaN              NaN                  NaN
9992                NaN              NaN                  NaN
9993                NaN              NaN                  NaN

      NumStorePurchases  NumWebVisitsMonth  AcceptedCmp3  AcceptedCmp4  \
0                   4.0                7.0           0.0           0.0
1                   2.0                5.0           0.0           0.0
2                  10.0                4.0           0.0           0.0
3                   4.0                6.0           0.0           0.0
4                   6.0                5.0           0.0           0.0
...                 ...                ...           ...           ...
9989                NaN                NaN           NaN           NaN
9990                NaN                NaN           NaN           NaN
9991                NaN                NaN           NaN           NaN
9992                NaN                NaN           NaN           NaN
9993                NaN                NaN           NaN           NaN

      AcceptedCmp5  AcceptedCmp1  AcceptedCmp2  Complain  Z_CostContact  \
0              0.0           0.0           0.0       0.0            3.0
1              0.0           0.0           0.0       0.0            3.0
2              0.0           0.0           0.0       0.0            3.0
3              0.0           0.0           0.0       0.0            3.0
4              0.0           0.0           0.0       0.0            3.0
...            ...           ...           ...       ...            ...
9989           NaN           NaN           NaN       NaN            NaN
9990           NaN           NaN           NaN       NaN            NaN
9991           NaN           NaN           NaN       NaN            NaN
9992           NaN           NaN           NaN       NaN            NaN
9993           NaN           NaN           NaN       NaN            NaN

      Z_Revenue  Response
0          11.0       1.0
1          11.0       0.0
2          11.0       0.0
3          11.0       0.0
4          11.0       0.0
...         ...       ...
9989        NaN       NaN
9990        NaN       NaN
9991        NaN       NaN
9992        NaN       NaN
9993        NaN       NaN

[9994 rows x 19 columns]>

In [5]:
marketing.drop(range(2240,9994),inplace=True)

In [6]:
marketing.isnull().sum()

Order ID                0
Marital_Status          0
Income                 24
Dt_Customer             0
Recency                 0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [7]:
marketing.describe()

,Income,Recency,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,52247.251354,49.109375,2.325000,4.084821,2.662054,5.790179,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,25173.076661,28.962453,1.932238,2.778714,2.923101,3.250958,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,35303.000000,24.000000,1.000000,2.000000,0.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,51381.500000,49.000000,2.000000,4.000000,2.000000,5.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,68522.000000,74.000000,3.000000,6.000000,4.000000,8.000000,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,666666.000000,99.000000,15.000000,27.000000,28.000000,13.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [8]:
marketing["Income"].fillna(marketing["Income"].mean(0),inplace=True)

C:\Users\vnshs\AppData\Local\Temp\ipykernel_12704\2047623748.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  marketing["Income"].fillna(marketing["Income"].mean(0),inplace=True)

In [9]:
marketing.isnull().sum()

Order ID               0
Marital_Status         0
Income                 0
Dt_Customer            0
Recency                0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64